language: go

go:
  - 1.9.x

script:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - overalls -project=github.com/ceshihao/testleak -covermode=count
  - goveralls -service=travis-ci -coverprofile=overalls.coverprofile
